# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Soon
    url: /
    weight: 11
  - name: Soon
    url: /
    weight: 12
  - name: Soon
    url: /
    weight: 13
  - name: Soon
    url: /
    weight: 20
  - name: Soon
    url: /
    weight: 30
  - name: Soon
    url: /
    weight: 40
